version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "${PORT:-4566}:4566"
      - "${PORT_WEB_UI-8089}:${PORT_WEB_UI-8080}"
    environment:
      SERVICES: s3,sqs,dynamodb
      DATA_DIR: /tmp/localstack/data
    volumes:
      - 'sqs:/tmp/localstack'
volumes:
  sqs: null
