service: prestissimo

provider:
  name: aws
  runtime: nodejs12.x

custom:
  bucketName: ${self:service}-${self:provider.stage}

plugins:
  - serverless-offline

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
      - "s3:PutObject"
      - "s3:GetObject"
    Resource: ${self.custom.bucketName}

functions:
  convert:
    handler: convert.handler
    events:
      - s3:
        bucket: ${self.custom.bucketName}
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/

resources:
  Resources:
    GeneralUseBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self.custom.bucketName}
