service: prestissimo

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: shared-private-bucket.alexjpaz.com
  environment:
    awsBucket: "${self:custom.bucketName}"

  provider:
    s3:
      stagingBucket:
        name: "${self:custom.bucketName}"
        corsConfiguration:
          corsRules:
            - allowedHeaders:
                - "*"
              allowedMethods:
                - PUT
                - POST
              allowedOrigins:
                - "*"

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: ${self:service}-${self:provider.stage}

plugins:
  - serverless-offline

functions:
  httpRouter:
    handler: src/http/index.router
    events:
      - http:
          path: "{proxy+}"
          method: any
      - http:
          path: "/"
          method: any
  convert:
    handler: handler.convert
    events:
      - s3:
          bucket: stagingBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/raw/
