service: prestissimo

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: ${self:service}-${self:provider.stage}

plugins:
  - serverless-offline

functions:
  httpRouter:
    handler: handler.http.router
    events:
      - httpApi: '*'
  convert:
    handler: handler.convert
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/raw/
