version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run postinstall:download-dependencies
            - setup_remote_docker
            - run: docker-compose up -d
            - run: npm test
            - run:
               name: docker-compose down
               command: docker-compose down -f
               when: always
            - run: npm run serverless:package
workflows:
    build-and-test:
      jobs:
        - build-and-test
