version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13
        environment:
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
      - image: localstack/localstack
        environment:
          DEBUG: 1
          SERVICES: s3,sqs
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'export PATH=./opt/:$PATH' >> $BASH_ENV
            - run: npm install
            - run: npm test
            - run: npm run serverless:package
  deploy:
    docker:
      - image: circleci/node:13
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'export PATH=./opt/:$PATH' >> $BASH_ENV
            - run: npm install
            - run: node_modules/.bin/serverless deploy --stage dev -v | tee deploy.out
            - run: BASE_URL=$(cat deploy.out | grep 'ServiceEndpoint' | awk '{ print $2 }') yarn test:integration
            - run: node_modules/.bin/serverless deploy --stage production -v | tee deploy.out
            - run: BASE_URL=$(cat deploy.out | grep 'ServiceEndpoint' | awk '{ print $2 }') yarn test:integration

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy:
            requires:
               - build-and-test
            context: "aws.amazon.com/alexjpaz/circleci"
            filters:
              branches:
               only: master
