version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13
        environment:
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
      - image: localstack/localstack
        environment:
          DEBUG: 1
          SERVICES: s3,sqs
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run postinstall:download-dependencies
            - run: ./scripts/wait-until-localstack-is-ready
            - run: ./scripts/provision-localstack
            - run: npm test
            - run: npm run serverless:package
workflows:
    build-and-test:
      jobs:
        - build-and-test
