version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13
        environment:
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
      - image: localstack/localstack
        environment:
          DEBUG: 1
          SERVICES: s3,sqs
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'export PATH=./opt/:$PATH' >> $BASH_ENV
            - run: npm install
            - run: npm run build
            - run: npm test
            - run: npm pack
  deploy:
    docker:
      - image: circleci/node:13
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'export PATH=./opt/:$PATH' >> $BASH_ENV
            - run: npm run build
            - run: ./scripts/serverless-deploy dev
            - run: ./scripts/serverless-deploy production
  deploy_branch:
    docker:
      - image: circleci/node:13
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'export PATH=./opt/:$PATH' >> $BASH_ENV
            - run: npm install
            - run: npm run build
            - run: ./scripts/serverless-deploy pr-${CIRCLE_PULL_REQUEST##*/}

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy_branch:
            requires:
               - build-and-test
            context: "aws.amazon.com/alexjpaz/circleci"
            filters:
              branches:
                only: /feature\/.*/
        - deploy:
            requires:
               - build-and-test
            context: "aws.amazon.com/alexjpaz/circleci"
            filters:
              branches:
               only: master
