---
authorizer:
  # FIXME - BAD NEWS BEARS
  usePassthrough: false
  audience: "https://prestissimo.alexjpaz.com"
  issuer: "https://alexjpaz.auth0.com/"
  jwksUri: "https://alexjpaz.auth0.com/.well-known/jwks.json"
